print('Hello World!')
print('What is your name? ')
my_name = input()
print('Your name is ' + my_name)
name = len(my_name)
print('Your name is ' + str(name) + ' letters long.')
print('How old are you? ')
age = input()
print('So you are ' + age + ' years old. That means that you will be ' + str(int(age) + 1) + ' next year.')
print('So nice to meet you' + my_name)
